### ISSUE TITLE
Parser trips over xml declarations (need to ignore or strip them)

### ISSUE THREAD

**Issue by kangax** [kangax/html-minifier#10]

**Comment by mhulse** [comment]
#63 ([Parse error with <?php ?>](https://github.com/kangax/html-minifier/issues/62)) seems related.

An ignore options object, or similar, could be useful to the end user.

If you're busy, I could help you tackle this ...  It seems like ignoring would be the way to go.

Any thought on where you'd want to implement "ignore" functionality?

**Comment by kangax** [comment]
@mhulse Ignore option is definitely a good idea. It would make sense to be able to define multiple chunks to ignore. For example, "<%= ... %>" and "<% ... %>", or "<?php ... ?>" or "<?xml ... ?>". But how to make it so that it ignores anything in between? Perhaps a regex.

**Comment by mhulse** [comment]
Awesome! I'll look into this and get back to you. Thanks for the feedback. :+1:

**Comment by mhulse** [comment]
So, here's where I'm at.

It's a work in progress, but here's the code:

https://github.com/mhulse/html-minifier/tree/patch-3/src

Most of the work is done here:

https://github.com/mhulse/html-minifier/blob/patch-3/src/htmlparser.js#L82-L90

Test input:

``` html
This is the start. <% ... %>
<%= ... %>
<? ... ?>
<!-- This is the middle, and a comment. -->
No comment, but middle.
<?= ... ?>
<?php ... ?>
<?xml ... ?>
Hello, this is the end!
```

Output:

``` html
This is the start.<% ... %><%= ... %><? ... ?>No comment, but middle.<?= ... ?><?php ... ?><?xml ... ?>Hello, this is the end!
```

It's working, but notice the lack of whitespace?

Check it out when I remove the "ignored" tags:

``` html
This is the start.No comment, but middle.Hello, this is the end!
```

Not optimal.

Because I patterned this patch after the code that handles HTML comments, I ran this test:

``` html
<!-- xxxx -->
ddd     
<!-- yyy -->
xxx
```

Output (without removing comments):

``` html
<!-- xxxx -->ddd<!-- yyy -->xxx
```

With comments removed:

``` html
dddxxx
```

Same whitesapce problem.

### Question(s):

First and foremost, how should we handle whitespace around "ignored" tags?

Secondly, Is there a better way to handle whitespace for when it comes to comments **and** "ignored" tags?

The problem is, the previous/next tags need to be sent to the `collapseWhitespaceSmart()` method, but `htmlparser.js` doesn't do that until a bit further down in the code (after the section that checks for comments, and now my code to check for "ignored" tags).

It's getting late, so I can't think of a good solution right now, but my gut is telling me that if we want to fix this, there's will have to be a refactoring of the `htmlparser.js` (maybe make it less procedural in that [particular section](https://github.com/mhulse/html-minifier/blob/patch-3/src/htmlparser.js#L64-L169)?).

On the other hand, I'm still wrapping my head around all of the code, so maybe there's an easy answer? Something that I'm overlooking?

With that said, I'm pretty sure comments behaved like above before I ever touched the code ... that tells me someone else ran into this situation and decided not to worry how whitespace collapses around comments; if that's the case, should I not be worried about how whitespace collapses around the "ignored" tags too?

Am I making any sense here?

I need to catch some zzzzzzs and come back to this code with a fresh start tomorrow. :)

**Comment by kangax** [comment]
Hey @mhulse sorry for late reply! (lots of work)

I'm just not understanding one thing — why do we care about removed whitespace?

If this:

```
<% if foo? %>
  <div class="bar">
    ...
  </div>
<% end %>
```

becomes this:

```
<% if foo? %><div class="bar">...</div><% end %>
```

..then we're good to go.

As far as I understand, it's exactly what we want. Or am I missing something?

**Comment by mhulse** [comment]
@kangax Ahhh, thanks for the example! :+1: 

I was personally working with PHP in mind (which would require the same type of logic, different tags of course, as you posted above), so it's good for me to see an example using tags other than PHP. 

Based on my current work, here's a real world example taken from a WordPress template:

``` html
<div>

    <article>

        <div>

            <div>

                <?php if (get_the_post_thumbnail()): ?>

                    <a href="<?=the_permalink()?>">

                        <?=the_post_thumbnail('thumbnail', array('class' => 'imgr'))?>

                    </a>

                <?php endif; ?>

                <header>

                    <p><time datetime="<?=get_iso_8601()?>"><?=the_time('g:i')?> <?=the_time('a')?></time></p>

                    <hgroup>

                        <?php

                            $category = get_the_category();
                            $category_name = $category[0]->cat_name;

                        ?>

                        <?php if (strtoupper($category_name) !== 'UNCATEGORIZED'): ?>

                            <h2><?=$category_name?></h2>

                        <?php endif; ?>

                        <h1><a href="<?=the_permalink()?>"><?=the_title()?></a></h1>

                    </hgroup>

                </header>

                <p><?=the_excerpt()?><?=edit_post_link('edit', ' [', ']')?></p>

            </div>

        </div>

    </article>

</div>
```

... gets converted to:

``` html
<div><article><div><div><?php if (get_the_post_thumbnail()): ?><a href="<?=the_permalink()?>"><?=the_post_thumbnail('thumbnail', array('class' => 'imgr'))?></a> <?php endif; ?><header><p><time datetime="<?=get_iso_8601()?>"><?=the_time('g:i')?><?=the_time('a')?></time></p><hgroup><?php

                            $category = get_the_category();
                            $category_name = $category[0]->cat_name;

                        ?><?php if (strtoupper($category_name) !== 'UNCATEGORIZED'): ?><h2><?=$category_name?></h2><?php endif; ?><h1><a href="<?=the_permalink()?>"><?=the_title()?></a></h1></hgroup></header><p><?=the_excerpt()?><?=edit_post_link('edit', ' [', ']')?></p></div></div></article></div>
```

### Question `#1`:

Does the above minification look good to you?

### Question `#2`:

I guess when I expressed concerns with whitespace, I was thinking of situations like:

``` html
<p><time datetime="<?=get_iso_8601()?>"><?=the_time('g:i')?> <?=the_time('a')?></time></p>
```

... which gets minified to:

``` html
<p><time datetime="<?=get_iso_8601()?>"><?=the_time('g:i')?><?=the_time('a')?></time></p>
```

Notice that the whitepsace between `the_time()` calls gets removed.

I wonder the best way to handle such a situation? Is this something I should be concerned about?

---

No worries on the late reply! This is the type of thing that we don't need to rush, so don't hesitate to take your time on helping me out. :octocat: 

Speaking of help, thanks for taking the time to give me some guidance, I really appreciate it. :smile:

---

One last thing, I noticed that there's another fork of this code that handles PHP tags:

https://github.com/nancoder/html-minifier/commit/af096e033382322849bb1400682255db0a740c0c

I've only had a chance to quickly look at his code, but I was happy to see that we pretty much headed down the same paths in terms of where we put our logic.

With that said, I had plans to download that fork and compare his code to mine ... I think our code is pretty similar (only, his focus was just PHP), but just in case he thought of something I missed, I figured it'd be worth the time to compare.

**Comment by mhulse** [comment]
Just tested your example code on my fork, and this:

```
<% if foo? %>
  <div class="bar">
    ...
  </div>
<% end %>
```

... gets converted to:

```
<% if foo? %><div class=bar>...</div><% end %>
```

Looks like we're close to having a patch.

I'll be sure to add this example code as a pass/fail test.

**Comment by kangax** [comment]
@mhulse Yep, that last example looks good.

**Comment by kangax** [comment]
@mhulse As far as Question #1, from cursory examination it appears to look good. As far as Question #2, I think it's best we address the whitespace issue (as in your example) later, once directive parsing is implemented, and once we have any additional requests for it.

**Comment by mhulse** [comment]
@kangax Sounds awesome. I'll be doing a PR tonight for your review.

Thanks much!
