### ISSUE TITLE
Question: State of the project

### ISSUE THREAD

**Issue by Chris2011** [kangax/html-minifier#1081]
Hey,

this is really just a question to figure out, whether this project is still alive or not. I see many tickets also about missing ES6 support, due to uglify (Seems old, maybe they already added it now but dunno) #1040. From the ticket I see this package: https://github.com/terser/html-minifier-terser so is html-minifier-terser the replacement of html-minifer or a plugin or what is it? What will be maintained? I need a maintained node package for my NetBeans plugin Minifierbeans: https://github.com/Chris2011/minifierbeans (https://github.com/Chris2011/minifierbeans/issues/66)

Thx :)

**Comment by DanielRuf** [comment]
> html-minifier-terser the replacement of html-minifer or a plugin or what is it

Hi, html-minifier-terser is html-minifier with terser instead of uglifyjs and other changes, including improvements. So it is basically a replacement, not a plugin for html-minifier.

So far html-minifier-terser is actively maintained but other things have a higher priority for me at the moment.

Afaik the webpack community and @evilebottnawi wanted to create a fork with terser 5 and some other changes. Not sure what the current status is.

**Comment by Chris2011** [comment]
Thx @DanielRuf. Great news so I will use html-minifier-terser. That's fine as the current state is as good as possible for my use.


Cheers

Chris
