### ISSUE TITLE
Combine repeated script/style tags

### ISSUE THREAD

**Issue by torvalde** [kangax/html-minifier#120]
Repeated tags like:

``` html
<script>console.log("hi");</script>
<script>console.log("hi");</script>
```

could be combined into:

``` html
<script>console.log("hi");console.log("hi");</script>
```

**Comment by kangax** [comment]
Good idea. It's not a completely safe modification, but we can add this as an option.

``` html
<script>console.log(typeof f)</script>
<script>function f(){}</script>
```

logs undefined

``` html
<script>console.log(typeof f); function f(){}</script>
```

logs function

etc.

**Comment by ghost** [comment]
In the case of CSS, this is 100% safe, and afaik, JavaScript is also safe, but under the assumptions that there aren't any errors that are caused by a definition in a later `<script>` tag being used in a previous one, and that `var` definitions don't share the same names.

**Comment by kangax** [comment]
@Undeterminant it's definitely can-of-worm-ish:

1) error handling
2) hoisting
3) var declaration conflicts

**Comment by ghost** [comment]
The main error problems are with syntax errors, because a syntax error in one script will propagate to the next. But, if you have a syntax error in one, you really shouldn't be doing minification in the first place.

I mean, script concatenation does not always preserve the same functionality, which is why it shouldn't be default, but as long as your code is fully-functional before hand, I wouldn't be too apprehensive about it unless you're using an older browser (like an old version of IE).

Considering how UglifyJS handles concatenating entire files properly, concatenating `<script>` tags shouldn't be an issue. I would recommend making it the default when `--minify-js` is on.

I also just tried uglifying the example that you gave and it did gave the exact "breaking" results that you gave. That's probably undefined behaviour (which is a reasonable guess), and supporting undefined behaviour seems like a bad idea.

**Comment by alexlamsl** [comment]
Reading the [specification](http://www.w3.org/TR/2011/REC-CSS2-20110607/cascade.html#cascade), then look at [one of our benchmarks](https://github.com/kangax/html-minifier/blob/gh-pages/benchmarks/amazon.html) suggests we can't easily combine `<style>` contents together either.

Just encountering the mix of `<style>`, `<link type='text/css'>` & `<noscript>` alone already makes my head spins :sweat:

**Comment by KenSharp** [comment]
I know it's not supported by the browsers (yet) but there's also `<style scoped>` to think about. The minifier would either need to know which parent element the scoped refers to, or just ignore it. Combining the `scoped`s together sounds like a nightmare.

**Comment by DamonHD** [comment]
A possibly related suggestion...

When the same async script is included in the document multiple times, such as for simple inclusion of Google AdSense code, it is in that case, and possibly in general OK, to omit the second and subsequent attempts to load the script, eg in:

    <script async src="//pagead2.googlesyndication.com/pagead/js/adsbygoogle.js"></script>
    <ins class="adsbygoogle"
    style="display:block"
    data-ad-client="ca-pub-XXX"
    data-ad-slot="YYYY"
    data-ad-format="auto"></ins>
    <script>
    (adsbygoogle = window.adsbygoogle || []).push({});
    </script>
    ....
    ....
    <script async src="//pagead2.googlesyndication.com/pagead/js/adsbygoogle.js"></script>
    <ins class="adsbygoogle"
    style="display:block"
    data-ad-client="ca-pub-XXX"
    data-ad-slot="YYYY"
    data-ad-format="auto"></ins>
    <script>
    (adsbygoogle = window.adsbygoogle || []).push({});
    </script>
    ....


it saves page weight and possibly some redundant Shift-RELOAD activity in my observation to omit the second:

    <script async src="//pagead2.googlesyndication.com/pagead/js/adsbygoogle.js"></script>

Rgds

Damon
