### ISSUE TITLE
`<!-- htmlmin:ignore -->` comments are left

### ISSUE THREAD

**Issue by XhmikosR** [kangax/html-minifier#176]
@kangax: shouldn't those be removed when `removeComments` is set to `true`?

**Comment by kangax** [comment]
Good point. They probably should.

**Comment by kangax** [comment]
On a second thought, I don't think they should be removed. Isn't the whole point to remove regular comments but leave other chunks of some "important" content (by surrounding them with "htmlmin:ignore" ones)?

**Comment by XhmikosR** [comment]
Well, the comments are not part of the important stuff one wants or
intended to keep. It makes no sense to keep them apart from debugging
maybe. Plus they add to the final size.

**Comment by madstuthemad** [comment]
I'm new to grunt as of yesterday and totally loving the fact it does what you want it to do first time - so thanks to you guys and the rest of the community!

Anyway I agree that this comment should be stripped like the rest. I was surprised to see it there since I had removeComments set to true. I think its counter-intuitive to keep these comments in but others out as there's nothing special about these ones and I don't need them in the minimised code.

**Comment by radkodinev** [comment]
+1
I completely agree that those comments should be removed.

**Comment by kangax** [comment]
@duncanbeevers If you could look into this, that would be awesome! Should be fairly trivial.
