### ISSUE TITLE
Any e.g. for the usage on some template minification such as handlebars or underscore?

### ISSUE THREAD

**Issue by hwoarangzk** [kangax/html-minifier#325]
I've read the article Experimenting with HTML minifier and the options used for html-minifier, but still wonder how to use some options like:customAttrAssign, customAttrSurround, customAttrCollapse.
So what's the usage of options customAttrAssign, customAttrSurround, customAttrCollapse if I want to use the template like the following? How to write these options? Thanks.
If my template is like:

```
<% if (true) {%>

<% } else { %>

<%}%>
<%
    var a = require('abc');
%>
    <%==obj.name%>
    <div class="class <%==obj.emptyClass%>">div</div>
```

**Comment by duncanbeevers** [comment]
When I try out that markup in the demo minifier http://kangax.github.io/html-minifier/, and minify using the default options, I get this output.

``` html
<% if (true) {%><% } else { %><%}%><% var a = require('abc'); %><%==obj.name%><div class="class <%==obj.emptyClass%>">div</div>
```

`customAttrAssign`, `customAttrSurround`, and `customAttrCollapse` are used to extend the html lexer so that it recognizes certain non-valid markup, as used in a number of contemporary web frameworks.

Each of the options has tests exercising their usage in the test suite, and include examples like these.

`customAttrAssign` is an array of RegExps, each of which is used to recognize custom markup for the assignation of a value to an html attribute.

``` html
<div flex?="{{mode != cover}}"></div>
```

`customAttrSurround` is an array of RegExp pairs, each of which is used to recognize custom markup surrounding html attributes.

``` html
<input {{#if value}}checked="checked"{{/if}}>
<input {{#if value1}}data-attr="example"{{/if}} {{#unless value2}}checked="checked"{{/unless}}>
```

`customAttrCollapse` is an array of RegExps, each of which is used to recognize an attribute name, and to strip newlines from matching attribute's values.

``` html
<div class="fragment square" ng-hide="square1.hide" ng-class="{
  'bounceInDown': !square1.hide,
  'bounceOutDown': square1.hide
}"></div>
```

**Comment by hwoarangzk** [comment]
What is html lexer? I'm from China and don't quite understand this word. 
What's the difference between writing customAttrAssign, customAttrSurround and customAttrCollapse and not writing these options if I use the template like the example in my question? 
Thank you :)

**Comment by duncanbeevers** [comment]
A lexer, or tokenizer, converts a string, such as an html document, into a collection of discrete, meaningful tokens, or nodes.

For example, a string might look like this `'<html></html>'`, and its representation as tokens might look like this. `[{ type: 'tag open', value: 'html' }, { type: 'tag close', value: 'html' }]`

As the program progresses along, consuming the input string, it produces a set of tokens like this. These tokens are then traversed, eliminated, and otherwise massaged, and finally they are used to reconstitute a modified html string.

For the examples I showed above, the lexer cannot ordinarily recognize that kind of input. It isn't valid HTML. In order to do something useful with that input the lexer is extended to recognize the parts of the input string and to generate new, or extended token types representing the markup.

Likewise, the serializer which reconstitutes the markup is extended to recognize the new tokens, and to produce appropriate markup representing them.

**Comment by hwoarangzk** [comment]
Thank you so much for your answer! That's really a lot of help :) And how could I write the options? 

customAttrAssign, customAttrSurround and customAttrCollapse should be written like:

<pre>customAttrAssign: [/\<%={0,2}/, /%\>/],
customAttrSurround : [/\<%={0,2}/, /%\>/],
customAttrCollapse : [/\<%={0,2}/, /%\>/]</pre>

Is this right?

**Comment by kangax** [comment]
You can now use `ignoreCustomFragments` option
