### ISSUE TITLE
event attributes issue

### ISSUE THREAD

**Issue by stevenvachon** [kangax/html-minifier#412]
if the html invalidly contains an attribute that starts with "on", such as "one" or "only", it'll be treated as an event attribute and uglified when `minifyJS===true`.

https://github.com/kangax/html-minifier/blob/gh-pages/src/htmlminifier.js#L105

I have a need for a library that provides a map of html event attributes, so I'll be writing such very soon. Lemme know if you're interested in using it.

**Comment by kangax** [comment]
Hmm... good catch. Unfortunately, I think map would still be a brittle solution (although perhaps less brittle than `/^on.*/`) due to vast number of events across different implementations — both standard and non-standard/proprietary, older and newer, deprecated and experimental, platform-specific, and so on.

**Comment by stevenvachon** [comment]
Agreed. For now, I have quickly covered HTML and SVG event attributes: [stevenvachon/event-attributes](https://github.com/stevenvachon/event-attributes)

There're some IE-specific events that could be added, though.

**Comment by alexlamsl** [comment]
If we were to implement a flag say `customEventAttributes` and default it to `/^on/`, would that addresses this?

I am asking because currently I have custom code minifying AngularJS attributes, and at least half of those can be combined with this custom flag if implemented.

(The other half being attributes that are expected to return a value, so the current `minifyjs` logic doesn't apply cleanly to it...)

**Comment by kangax** [comment]
I think it wouldn't hurt to expose it.
