### ISSUE TITLE
html-minifier and valid content in <object> tags?

### ISSUE THREAD

**Issue by matt-bailey** [kangax/html-minifier#51]
This is following on from my comment here: https://github.com/kangax/html-minifier/issues/45#issuecomment-16399390

I've done a little more experimenting and discovered that certain html tags work inside `<object>` tags and others don't (they are moved to after the object tag).

For example, `<img>`, `<span>` and `<i>` all work ok, but `<p>` and `<div>` don't, i.e. inline level elements work, but not block level.

Having read up a little more on the `<object>` tag apparently you are allowed zero, or any number of `<param>` elements, plus 'transparent' content, i.e. content that is valid HTML5 even if these tags are removed.

I suspect therefore, that html-minifier is acting as intended and merely respecting valid html markup, but if you have any other insight into this I'd love to know :)

**Comment by jfaissolle** [comment]
I think this is because some tags are wrongly registered in htmlparser. I have the same problem with the `<iframe>` tag. This one as well as the `<object>` tag are registered as block level (correct) as well as inline elements (wrong). If you remove them from the inline list in htmlparser.js, it works fine.

**Comment by jfaissolle** [comment]
I just submitted a pull request: #52

**Comment by matt-bailey** [comment]
Good stuff, well spotted.
