### ISSUE TITLE
a bug with removeComments&&ignoreCustomFragments

### ISSUE THREAD

**Issue by kath4job** [kangax/html-minifier#511]
![image](https://cloud.githubusercontent.com/assets/10356581/13350234/d5470290-dcb9-11e5-984e-7e73af94cede.png)
![image](https://cloud.githubusercontent.com/assets/10356581/13350269/0ca3dbd2-dcba-11e5-8a7c-3906018e754f.png)
when deciding whether to ignore this comment, the "text" has been replaced by "reCustomIgnore".
![image](https://cloud.githubusercontent.com/assets/10356581/13350297/309fdb58-dcba-11e5-995d-25a14d727e9b.png)
so this logic will never retrn true, this comment will be removed and cause some problems. my point of view, this function should be according to the following:
![image](https://cloud.githubusercontent.com/assets/10356581/13350205/a41af992-dcb9-11e5-924c-f08b2e2276af.png)
![image](https://cloud.githubusercontent.com/assets/10356581/13350371/8cf223de-dcba-11e5-8243-c19888e2ef7a.png)

**Comment by alexlamsl** [comment]
I'm confused - why should `ignoreCustomComments` be using a variable from `ignoreCustomFragments`?

**Comment by kath4job** [comment]
@alexlamsl ? this include **ignoreCustomComments** comment can't be removed, if it removed, it will cause the **ignoreCustomComments** replace back logic error.
![image](https://cloud.githubusercontent.com/assets/10356581/13350883/ecfb9c3a-dcbd-11e5-93ff-a0ab3cf65aec.png)

**Comment by alexlamsl** [comment]
Bear with my confused soul... :cold_sweat: 

Would you mind giving an example of html code (and options) that would produce an unexpected result?

**Comment by kath4job** [comment]
before htmlminfier:
![image](https://cloud.githubusercontent.com/assets/10356581/13351937/107fc120-dcc5-11e5-93c4-484fa7ba275d.png)
after : 
![image](https://cloud.githubusercontent.com/assets/10356581/13351963/33c91e1a-dcc5-11e5-85d8-c5fd4d3d0663.png)
options: 
![image](https://cloud.githubusercontent.com/assets/10356581/13351973/43d09658-dcc5-11e5-8579-f95a339ab333.png)

**Comment by alexlamsl** [comment]
Ah, I see what you mean now - when `ignoreCustomFragments` matches something in the comments, and `removeComments` is used, then we hit a replacement issue.

Just to be clear, is the following output what you'd expect instead?

```
{{if a==1}}<div>i'm a div</div>{{/if}}
```

**Comment by kath4job** [comment]
@alexlamsl   yes

**Comment by alexlamsl** [comment]
ok - will have a look at it :+1: 

@kangax this bug / corner case exists since `ignoreCustomFragments` is [introduced](https://github.com/kangax/html-minifier/commit/99823dfd1983502c84dfd2b0be0cde85a7cf17e6) - what are your thoughts on this? Do you agree with the expected results as stated above?

**Comment by kangax** [comment]
@kath4job for the future, it would be best to phrase an issue like this by simply stating that `<!-- {{ test }} -->{{if ... }}<p>...</p>{{/if}}` unexpectedly removes `<!-- {{ test }} -->` when "ignoreCustomFragments" is on. Took me a while to figure out what the problem is...

It's an interesting use case and I think the right outcome here is for minifier to strip a comment:

```
{{if ... }}<p>...</p>{{/if}}
```

Even though "ignoreCustomFragments" is on, we can't be aware of an outer context. If we try to parse input as HTML first — to be aware of the context — then we run into the issue of that markup not being valid HTML due to the presence of all that stuff that has to be ignored, and the entire parsing process goes to hell.

It's a catch 22.

For this reason, we can only ignore custom fragments as the very first step of minification, before trying to parse/minify anything. After that, `removeComments` logic kicks in. Two of these processes are independent and are unaware of each other, hence the removed fragment. In other words, `removeComments` takes precedence because it runs **after** `ignoreCustomFragments`.

We should definitely mention this in the docs but I think this is the correct behavior.

@kath4job @alexlamsl what do you think? Does this make sense? Is there anything else we can do without shooting ourselves in the foot?

**Comment by alexlamsl** [comment]
@kangax in terms of expected behaviour we are on the same page.

You might already know, but just in case I'd like to clarify that the bug is not just comment being removed. It is this:

```
<!--{{comment}}-->{{if}}blah{{/if}}
```

getting turned into this:

```
{{comment}}blah{{if}}
```

due to the assumption of sequential replacement.

I have an idea to fix this (the suggested fix above doesn't give our expected outcome...) - will post as soon as I'm back to a real keyboard.

**Comment by kangax** [comment]
Yep, I figured that. Thanks for taking care of it!
