### ISSUE TITLE
html that crashes the parser

### ISSUE THREAD

**Issue by zhekaus** [kangax/html-minifier#591]
html `<div><b><<[= {{app.name}} =]>></b></div>` crashes the parser

**Comment by alexlamsl** [comment]
I tried your example here and `html-minifier` doesn't crash. It reports an error due to the unescaped `<`, which isn't valid HTML Suggested fix:

``` html
<div><b>&lt;&lt;[= {{app.name}} =]>></b></div>
```

@kangax we are getting quite a few of these reports over time. What's your opinion on making the HTML parser more relaxed, matching web browsers (non-standard) behaviours?

**Comment by kangax** [comment]
I just want us to be cautious and try not to dig ourselves into a hole with all the extra and extra flexibility. Historically, html-minifier needed properly escaped input. If we can add support for browser-like behavior (and what kind of behavior is it anyway? don't browsers follow html5 one? or do they diverge?) without much hassle, let's try it.

**Comment by alexlamsl** [comment]
@kangax so for instance the example above would render just fine on any browsers that I have come across so far, even the older ones. But I agree we need to be extra cautious with this exercise.

**Comment by alexlamsl** [comment]
Anyway, this report itself isn't valid as the parser doesn't crash, so closing.
