### ISSUE TITLE
Add option to collapse all whitespace to 1 character, instead of completely removing it (to preserve empty text nodes)

### ISSUE THREAD

**Issue by kangax** [kangax/html-minifier#6]

**Comment by sparanoid** [comment]
+1 for trim whitespace to 1 character.

**Comment by stevenvachon** [comment]
If this library does not already convert multiple blank lines and spaces within `<body>` to a single space, then this is a _very_ important one. Because the browser renders

``` html
<strong>asdf</strong>asdf
```

differently than

``` html
<strong>asdf</strong> asdf
```

**Comment by kangax** [comment]
Currently, you can set `collapseWhitespace` to `false` and so:

``` html
<strong>asdf</strong>   asdf
```

would stay as:

``` html
<strong>asdf</strong>   asdf
```

while, with `collapseWhitespace` set to `true`, it'd become:

``` html
<strong>asdf</strong>asdf
```

The feature in this issue would give more granularity.

**Comment by stevenvachon** [comment]
HTML is more picky than that, though. For example, multiple spaces within `<pre>` are rendered, while those in any other tag are not. Special cases would be necessary.

**Comment by kangax** [comment]
Of course. That's why `<pre> foo bar </pre>` stays as `<pre> foo bar </pre>` even with `collapseWhitespace` set to `true` :) Also see https://github.com/kangax/html-minifier/blob/gh-pages/src/htmlminifier.js#L244-L246 and https://github.com/kangax/html-minifier/blob/gh-pages/src/htmlminifier.js#L37-L62

**Comment by stevenvachon** [comment]
Very cool :)

**Comment by mattaningram** [comment]
It doesn't make any sense that I can't stop htmlmin from collapsing whitespace inside of text elements. This was a standard feature on a non-grunt html minifier from 4 years ago.

At least give us the ability to collapse to a single white space, because if I want spans in a header element htmlmin screws me over every time. Either I use nbsp; and the header doesn't wrap, or I use normal white space, and it renders wrong when I use htmlmin.

Please add this feature, I can't find any alternative that is clean.

**Comment by kangax** [comment]
Actually, we already do leave one space around, even with `collapseWhitespace=true`

``` html
<strong>asdf</strong>   asdf
```

becomes:

``` html
<strong>asdf</strong> asdf
```

**Comment by kangax** [comment]
@mattaningram can you give an example of what you'd like always-leave-one-whitespace behavior to be? What would these minify to?

``` html
<b>foo</b>
<b>   foo</b>
<b>foo</b>bar
<b>foo</b>   bar
<b> </b>
```

**Comment by stevenvachon** [comment]
If that were all in a single document, it should produce:

``` html
<b>foo</b> <b> foo</b> <b>foo</b>bar <b>foo</b> bar <b> </b>
```

Whitespace within `<pre>` should be preserved.

**Comment by ghost** [comment]
+1. The behavior should be "collapse to one space" instead of completely removing spaces. Here is a real-world example using Bootstrap:

My local development, no minification:
![Development](https://cloud.githubusercontent.com/assets/340401/2787042/0ec29ae2-cb83-11e3-9886-1d9ae7c12345.png)

Production env, after minification:
![Prodution](https://cloud.githubusercontent.com/assets/340401/2787052/64b97aba-cb83-11e3-9c91-58c98ad038a1.png)

Since there's no space left between elements (checkbox and text, button and button), the margin is gone, leaving an ugly look. Setting `collapseWhitespace` to `false` avoids the problem, but clearly is not a fix.

**Comment by kangax** [comment]
@Phoenixheart can you paste your markup for that example?

**Comment by kangax** [comment]
@stevenvachon the only difference is in `<b> </b>` then (right now minifier produces `<b></b>`; no space inside).

**Comment by kangax** [comment]
So... since `<strong>asdf</strong>   asdf` already collapses to `<strong>asdf</strong> asdf` (note the space) what other issues are left here?

**Comment by stevenvachon** [comment]
@kangax that could present a problem in situations such as:

``` html
<b>foo</b><b>
bar</b>
```

``` html
<b>foo</b>
<b>bar</b>
```

which should produce:

``` html
<b>foo</b><b> bar</b>
```

``` html
<b>foo</b> <b>bar</b>
```

but instead produce:

``` html
<b>foo</b><b>bar</b>
```

which renders as:
**foobar**
instead of:
**foo bar**

**Comment by ghost** [comment]
@kangax Here you go:

``` html
  <div class="form-group">
    <label>
      <input type="checkbox" name="is_private" ng-model="entry.is_private">
      This entry is private (visible to only me)
    </label>
  </div>

  <div class="form-group">
    <input type="submit" class="btn btn-primary" value="Update" ng-disabled="editForm.$invalid || editForm.$pristine">
    <a class="btn btn-default" ng-click="cancel()">Cancel</a>
  </div>
```

**Comment by kangax** [comment]
@stevenvachon This one:

``` html
<b>foo</b>
<b>bar</b>
```

already produces:

``` html
<b>foo</b> <b>bar</b>
```

but:

``` html
<b>foo
</b>
```

becomes:

``` html
<b>foo</b>
```

So together with @Phoenixheart's example, there's 2 problems:

``` html
<b>foo
</b>
```

and

``` html
<input>
test
```

**Comment by kangax** [comment]
Fixed in https://github.com/kangax/html-minifier/commit/e9ab0794e7fd31f8f10f15f5346395c5e0affdf8

**Comment by stevenvachon** [comment]
Thanks!

**Comment by ghost** [comment]
Awesome, thanks. Does this fix apply for the "two buttons" problem too?

**Comment by webnard** [comment]
Thanks, @kangax!
