### ISSUE TITLE
Support for HTML5 boolean attributes

### ISSUE THREAD

**Issue by dalgard** [kangax/html-minifier#63]
I haven't gone into this extensively, but you should at least consider adding `autofocus` to your list of boolean attributes. Thanks :)

**Comment by kangax** [comment]
autofocus, multiple, required, hidden, contenteditable, spellcheck. Any other ones? [Don't see anything else](http://dev.w3.org/html5/markup/global-attributes.html)

/cc @mathiasbynens

**Comment by dalgard** [comment]
Looks reasonable - awesome.

**Comment by mathiasbynens** [comment]
For future reference, the current list of boolean attributes in this HTML minifier is [the following](https://github.com/kangax/html-minifier/blob/20df2c1a9e989507267a2c81ecd1a315a7ec8a6b/src/htmlparser.js#L48-L49):

``` js
"checked,compact,declare,defer,disabled,ismap,multiple,nohref,noresize,noshade,nowrap,readonly,selected"
```

> autofocus, multiple, required, hidden, contenteditable, spellcheck. Any other ones?

[`contenteditable`](http://www.whatwg.org/specs/web-apps/current-work/multipage/editing.html#attr-contenteditable) and [`spellcheck`](http://www.whatwg.org/specs/web-apps/current-work/multipage/editing.html#attr-spellcheck) aren’t proper boolean attributes, although they do get a default value other than the empty string.

Hmm, `async`, `itemscope`, and `seamless` come to mind, but there are probably more…

**Comment by mathiasbynens** [comment]
**Update:** 

``` bash
$ curl -s "http://www.whatwg.org/specs/web-apps/current-work/" | grep -C 3 "boolean\s*attribute"
```

`reversed`, `allowfullscreen`, `typemustmatch`, `muted`, `sortable`, `novalidate`, `formnovalidate`, `open`, `default`, `inert`, `truespeed` (along with all the others mentioned in this thread). There may be even more.

Here’s the full list so far:

```
allowfullscreen
async
autofocus
checked
compact
declare
default
defer
disabled
formnovalidate
hidden
inert
ismap
itemscope
multiple
multiple
muted
nohref
noresize
noshade
novalidate
nowrap
open
readonly
required
reversed
seamless
selected
sortable
truespeed
typemustmatch
```

For any of these attributes, `attributename="any-value"` can be optimized into just `attributename`.

Then, there are a few non-boolean attributes that take a default value instead of the non-empty string:

```
contenteditable
spellcheck
```

Variations of `contenteditable="true"` and `contenteditable=""` can be optimized into just `contenteditable`. Any other values for this attribute that are not equal to the literal string `false` map to the default state, meaning e.g. `contenteditable="lolwat"` or `contenteditable=" true"` (with leading space) can be optimized by just removing the attribute completely.

Variations of `spellcheck="true"` and `spellcheck=""` can be optimized into just `spellcheck`. Any other values for this attribute that are not equal to the literal string `false` map to the default state, meaning e.g. `spellcheck="lolwat"` or `spellcheck=" true"` (with leading space) can be optimized by just removing the attribute completely.

**Comment by kangax** [comment]
Thanks @mathiasbynens. So we're 19 attributes short now.

```
[ ] allowfullscreen
[ ] async
[ ] autofocus
[x] checked
[x] compact
[ ] contenteditable
[x] declare
[ ] default
[x] defer
[x] disabled
[ ] formnovalidate
[ ] hidden
[ ] inert
[x] ismap
[ ] itemscope
[x] multiple
[ ] muted
[x] nohref
[x] noresize
[x] noshade
[ ] novalidate
[x] nowrap
[ ] open
[x] readonly
[ ] required
[ ] reversed
[ ] seamless
[x] selected
[ ] sortable
[ ] spellcheck
[ ] truespeed
[ ] typemustmatch
```

**Comment by mathiasbynens** [comment]
[`contenteditable` is not a boolean attribute.](http://www.whatwg.org/specs/web-apps/current-work/multipage/editing.html#attr-contenteditable) Updated the list.

**Comment by kangax** [comment]
It could be an empty string (or empty attribute), according to [this](http://dev.w3.org/html5/markup/global-attributes.html#common.attrs.contenteditable)

**Comment by mathiasbynens** [comment]
True, that’s what it says in the WHATWG HTML spec too (“The empty string and the `true` keyword map to the `true` state”). `spellcheck` [isn’t a boolean attribute either](http://www.whatwg.org/specs/web-apps/current-work/multipage/editing.html#attr-spellcheck), although it has similar behavior.

Just saying, we’re just not looking for boolean attributes here, but also for enumerated attributes that get a default value instead of the empty string. My `grep` trick definitely didn’t catch all of these.

**Comment by evilpie** [comment]
This might also be interesting. Most of the boolean attributes in Firefox. http://mxr.mozilla.org/mozilla-central/search?string=attribute+boolean&regexp=1&find=%2Fdom%2Fwebidl&findi=&filter=^[^\0]*%24&hitlimit=&tree=mozilla-central (Still misses DOMWindow or something)

**Comment by mathiasbynens** [comment]
@alrra found another attribute that can be optimized: [`draggable`](http://www.whatwg.org/specs/web-apps/current-work/multipage/dnd.html#the-draggable-attribute). It’s not a boolean attribute, but its missing default value is `auto`. So, the HTML minifier could optimize e.g. `draggable="auto"` into just `draggable`.

**Comment by jefffis** [comment]
How's about the `scoped` attribute for the style tag?

**Comment by tobaco** [comment]
download ?

**Comment by jefffis** [comment]
I think `download` needs a string pointing to the actual downloadable file.

**Comment by ahmedelgabri** [comment]
`autocorrect` & `autocapitalize`?

**Comment by evilpie** [comment]
For `download` the value is an optional filename. So just `download` still forces a download of the resource specified by `href`. (I implemented this feature in Firefox)

**Comment by jefffis** [comment]
Ahh, good to know -- thanks for the tip =)

**Comment by ditman** [comment]
What about `autocomplete`?

[HTML5 Spec: The autocomplete attribute](http://www.w3.org/TR/html5/forms.html#the-autocomplete-attribute)

(You'd probably need to inspect the parent form to evaluate properly the "default" (empty) state, so not sure that you'd want to minimize this :disappointed:)

**Comment by mathiasbynens** [comment]
@tobaco `<a download="">` being the same as `<a download>` is nothing special; this applies to all HTML attributes. The HTML minifier can optimize all instances of empty attribute values to just the attribute name without an explicit value.

**Comment by icoloma** [comment]
`autocomplete` is [moving to something other than on / off](http://www.whatwg.org/specs/web-apps/current-work/multipage/association-of-controls-and-forms.html#autofilling-form-controls:-the-autocomplete-attribute), so not sure if it's a good idea to add it to the list. OTOH, that could happen with almost any boolean attribute.

**Comment by freddyb** [comment]
`sandbox` (for iframes) has  a default value, when left blank. does this count as boolean by your definition?

**Comment by mathiasbynens** [comment]
So no optimizations for boolean-like attributes? Should there be a separate issue for that?

**Comment by kangax** [comment]
Yeah, I'd like to revisit those separately; look into optimizations of
contenteditable-like attributes.

**Comment by mckamey** [comment]
I was searching for a similar list when I came upon this discussion. I thought you might benefit from an updated list. I started with @mathiasbynens' idea to grep the spec but modified it to only look within the IDL blocks and look at the single-page spec. Then I stripped all the markup and removed every readonly attribute (since these can't be set via markup). I sorted / deduped and this is what I am seeing. Note that it includes a few `<video>` and `<audio>` tag attributes which aren't present in your list as of 10 months ago.

```
$ curl -s "http://www.w3.org/TR/html51/single-page.html" | grep "attribute boolean" > boolean.txt
```

```
allowFullscreen
async
autofocus
autoplay
checked
compact
controls
declare
default
defaultChecked
defaultMuted
defaultSelected
defer
disabled
draggable
enabled
formNoValidate
hidden
indeterminate
inert
isMap
itemScope
loop
multiple
muted
noHref
noResize
noShade
noValidate
noWrap
open
pauseOnExit
readOnly
required
reversed
scoped
seamless
selected
sortable
spellcheck
translate
trueSpeed
typeMustMatch
visible
```

You will probably want to lowercase these for your purposes. Thanks for the starter ideas.

**Comment by kangax** [comment]
@mckamey thanks! now we just need to find out which ones are not already in minifier's list.

**Comment by mckamey** [comment]
Shouldn't that be as easy as cutting and pasting over the top of the current list?

```
function isBooleanAttribute(attrName) {
    return (/^(?:allowfullscreen|async|autofocus|autoplay|checked|compact|controls|declare|default|defaultchecked|defaultmuted|defaultselected|defer|disabled|draggable|enabled|formnovalidate|hidden|indeterminate|inert|ismap|itemscope|loop|multiple|muted|nohref|noresize|noshade|novalidate|nowrap|open|pauseonexit|readonly|required|reversed|scoped|seamless|selected|sortable|spellcheck|translate|truespeed|typemustmatch|visible)$/).test(attrName);
}
```

Then just verify all looks good with diff before committing.

**Comment by mckamey** [comment]
If you prefer the list:

```
[ ] allowfullscreen
[ ] async
[ ] autofocus
[x] autoplay
[ ] checked
[ ] compact
[x] controls
[ ] declare
[ ] default
[x] defaultchecked
[x] defaultmuted
[x] defaultselected
[ ] defer
[ ] disabled
[x] draggable
[x] enabled
[ ] formnovalidate
[ ] hidden
[x] indeterminate
[ ] inert
[ ] ismap
[ ] itemscope
[x] loop
[ ] multiple
[ ] muted
[ ] nohref
[ ] noresize
[ ] noshade
[ ] novalidate
[ ] nowrap
[ ] open
[x] pauseonexit
[ ] readonly
[ ] required
[ ] reversed
[x] scoped
[ ] seamless
[ ] selected
[ ] sortable
[x] spellcheck
[x] translate
[ ] truespeed
[ ] typemustmatch
[x] visible
```

**Comment by kangax** [comment]
Thanks, updated.
