### ISSUE TITLE
Doesn't collapse empty crossorigin attribute

### ISSUE THREAD

**Issue by tinovyatkin** [kangax/html-minifier#728]
Currently it converts boolean `crossorigin` to `crossorigin=""` - that makes no sense, as empty value and lack of value both fallbacks to `crossorigin="anonymous"`, so, I think it make sense in case of missing value count `crossorigin` as boolean attribute and handle as per `collapseBooleanAttributes`?

**Comment by alexlamsl** [comment]
Reading on [MDN](https://developer.mozilla.org/en-US/docs/Web/HTML/CORS_settings_attributes) `crossorigin` does not look like a boolean attribute to me.

In any case, `html-minifier` currently does not optimise this one way or another.

**Comment by tinovyatkin** [comment]
Well, even MDN is very good, but it's not an official spec. On the W3C specs, however, `crossorigin` is used as boolean: [rel=preload spec](https://w3c.github.io/preload/).
Currently `html-minifier` changing this attribute from boolean form `crossorigin` to `crossorigin=""` - that's working, but apart of being longer it's not more correct (as MDN lists it must be `crossorigin="anonymous"`)...

**Comment by alexlamsl** [comment]
I care less about written specifications than how web browsers behave and what they actually support, which MDN tends to be fairly good at reporting. FWIW, [MSDN](https://msdn.microsoft.com/en-us/library/dn254950%28v=vs.85%29.aspx) also reports it as a string rather than boolean.

How certain are we that omitting the value would work across all the browsers that support `crossorigin`? IIRC you can't just omit a string attribute value in general.

**Comment by alexlamsl** [comment]
Closing for now as this is working as expected with the current browsers. If/when the situation changes, we shall re-visit this issue.

**Comment by kevincox** [comment]
Can we reconsider this? Omitting the value is equivalent to the empty string and the empty string is explicitly documented to be equivalent to "anonymous" https://developer.mozilla.org/en-US/docs/Web/HTML/Attributes/crossorigin All of the browsers that I have tested handle this case properly.
