### ISSUE TITLE
html with custom fragments compression incorrect

### ISSUE THREAD

**Issue by nuintun** [kangax/html-minifier#767]
>html-minifier options
```js
{
  minifyCSS: false,
  removeComments: true,
  useShortDoctype: true,
  collapseWhitespace: true,
  trimCustomFragments: true,
  conservativeCollapse: false,
  removeEmptyAttributes: true,
  collapseBooleanAttributes: true,
  customAttrCollapse: /<%={1,2}.+?%>/,
  ignoreCustomFragments: [/<%={0,2}.+?%>/],
  customAttrSurround: [[/<%[^=].*?%>/, /<%[^=].*?%>/]]
}
```

>html
```html
<button class="ui-button"
  <%= @autofocus ? 'autofocus' : '' %>
  style="width: <%= @width %>; height: <%= @height %>;">
  <%== @value %>
</button>
```

>expect output
```html
<button class="ui-button" style="width: <%= @width %>; height: <%= @height %>;" <%= @autofocus ? 'autofocus' : '' %>><%== @value %></button>
```

>actual output
```html
<button class="ui-button" style="width:<%= @width %>;height:<%= @height %>"<%= @autofocus ? 'autofocus' : '' %>><%== @value %></button>
```

```minifyCSS: false``` still remove last ```;```.

```<%= @width %>``` is attr and ```<%= @autofocus ? 'autofocus' : '' %>``` is attr value, 
but the space still have been removed.

**Comment by alexlamsl** [comment]
Trimming whitespace and trailing semi-colon is a separate optimisation to `style="..."`, and in fact introduced before `minifyCSS`: https://github.com/kangax/html-minifier/commit/60addbb1bdf83eb851d8c4ec7cb65722ddc7cabd - is this breaking anything in the browser?

As for the whitespace being removed around custom fragments, that's because you've specified `trimCustomFragments: true`.

**Comment by nuintun** [comment]
I think if custom fragments is attr or attr value, the whitespace can't been removed if not ```removeTagWhitespace: true```, and i also set:
```js
{  
  customAttrCollapse: /<%={1,2}.+?%>/,
  ignoreCustomFragments: [/<%={0,2}.+?%>/],
  customAttrSurround: [[/<%[^=].*?%>/, /<%[^=].*?%>/]]
}
```

**Comment by alexlamsl** [comment]
`trimCustomFragments` acts on custom fragments without any context information - and to be fair it cannot really reliably work that out since those bits do not have to conform to HTML in the first place.

If you have some ideas to improve upon the current behaviour, please send in a pull request and we can discuss about that. Other than that, since we have determined there isn't any bugs with the current implementation, I shall be closing this issue.
