### ISSUE TITLE
3.3.0 seems to have caused some breakages

### ISSUE THREAD

**Issue by redbugz** [kangax/html-minifier#775]
The 3.3.0 release seems to have broken some things in some of our components. Reverting to 3.2.3 seems to have solved the problem.

We don't have any details yet, and I know it stinks to have an issue with no details, but we are trying to identify what broke and we will add more details as soon as we discover what happened.

We just wanted people to be aware in the meantime.

**Comment by alexlamsl** [comment]
Read [your fork's commit](https://github.com/fs-webdev/gulp-htmlmin/commit/7060946322ff33df25cfa0e0a276d845c08f3cb9#comments) for context, seems to be something to do with `clean-css`.

Please open an issue with `clean-css` for such issues as they are discovered. Of course if it turns out to be related to `html-minifier`, leave a comment and I'll reopen this issue.
