### ISSUE TITLE
Quotes being removed from attributes containing slashes, which results in invalid HTML

### ISSUE THREAD

**Issue by nosachamos** [kangax/html-minifier#783]
According to the HTML spec (https://www.w3.org/TR/html401/intro/sgmltut.html#h-3.2.2), quotes may be removed only from attribute values containing "only contain letters (a-z and A-Z), digits (0-9), hyphens (ASCII decimal 45), periods (ASCII decimal 46), underscores (ASCII decimal 95), and colons (ASCII decimal 58)".

However, an attribute like so:

`href="/blog"` ends up with the quotes removed, resulting in an invalid HTML fragment like so:

`<a href=/blog></a>`

...as you can see, that slash causes confusing with tag closing slashes. This makes it impossible to use this feature when preprocessing angular templates, for example. The compiler blows up on the invalid HTML.

We should not remove quotes from attributes containing slashes or back slashes, or any other character not included in the ones mentioned in the spec.

**Comment by alexlamsl** [comment]
The current behaviour is based on https://mathiasbynens.be/notes/unquoted-attribute-values

Please demonstrate a case where a _web browser_ would fail to parse the minified HTML. Otherwise file a bug with the corresponding software library instead.

Especially since not enabling `removeAttributeQuotes` is a valid workaround, if I understand you correctly.
