### ISSUE TITLE
Breaking Angular inline styles

### ISSUE THREAD

**Issue by hillmanov** [kangax/html-minifier#788]
I will try to come up with a reproducible case that can be placed online, but after hours of digging I found that when the html-webapack-plugin which uses this module uses `v3.3.3` instead of `v.3.2.3`, my inline Angular styles were breaking when my code was minified. 

We are doing something like this: 

```
<div style="{{ background: item.color }}">Text</div>
```

After going through the minifier, all that is left is 

```
<div style="{}">Text</div>
```

This was the most obvious thing that broke, but I imagine there are other thing that could potentially break as well. Could this be caused by another dependency of html-minifier itself? 

I am not sure which version this was introduced, as I only found that if I went back down to 3.2.3 in my yarn.lock file manually the problem not longer was present.

**Comment by alexlamsl** [comment]
Just to make sure - have you enabled `minifyCSS`?

If so, you are passing `{{ background: item.color }}` directly to [clean-css](https://github.com/jakubpawlowicz/clean-css), which I supposed have a difference in behaviour when processing this otherwise invalid piece of CSS code.

Consider using [`ng-style`](https://docs.angularjs.org/api/ng/directive/ngStyle) for your Angular Expressions instead.

**Comment by hillmanov** [comment]
I will see if I can find out what webpack is doing with the html-webpack-plugin (which uses this module) when in production mode, and will see if there is a way I can pass in my own custom options.

**Comment by alexlamsl** [comment]
Closing for now as nothing is found against `html-minifier`. Please re-open if there is any new discovery with respect to this issue.
