### ISSUE TITLE
Module "./htmlparser" not found error.

### ISSUE THREAD

**Issue by pilwon** [kangax/html-minifier#84]
Looks like `global.HTMLParser` doesn't get set properly in some node.js environment. [This line](https://github.com/kangax/html-minifier/blob/a7e68a6f87c327fd0aed2d1261503539d64c9a46/dist/all.js#L393) fails and outputs this error message:

<blockquote>
Error: module "./htmlparser" not found from "./node_modules/rhtml/node_modules/html-minifier/dist/all.js"
</blockquote>

Please set `main` in `package.json` to actual source directory to better support NodeJS. You can distribute client-side library via bower.

**Comment by kangax** [comment]
But main in package.json is already set to "./dist/all.js" which is a distribution file.

**Comment by pilwon** [comment]
@kangax Yeah and my suggestion was to point that to `./src/htmlminifier.js` instead. For some reason `require('./htmlparser')` in `dist/all.js` fails to work.

**Comment by kangax** [comment]
@pilwon But ./src/htmlminifier.js is just one of 3 required files for a complete version of minifier (there's also parser and linter)

**Comment by pilwon** [comment]
@kangax,

### Problem

<blockquote>
Error: module "./htmlparser" not found from "./node_modules/rhtml/node_modules/html-minifier/dist/all.js"
</blockquote>

### Solution

Set `main` in `package.json` to actual source file (`./src/htmlminifier.js`). Note that `main` variable set in `package.json` is just an entry point for your module. Node.js **WILL** correctly handle file dependencies via `require(...)` so all 3 required files will be used.

For whatever reason you pointed to the minified/combined file (`./dist/all.js`) and this would have been fine as long as you packaged it correctly. However for some reason `global.HTMLParser` doesn't get set properly in some node.js environment and [require('./htmlparser')](https://github.com/kangax/html-minifier/blob/a7e68a6f87c327fd0aed2d1261503539d64c9a46/dist/all.js#L393) fails to work. Therefore I see the above error message.

After making the suggested change, it no longer outputs an error message.

**Comment by kangax** [comment]
> I will recap the issue I repeatedly explained above for the last time.

Sorry, but where did you _repeatedly_ explain it? I only asked to clarify once, and you repeated your suggestion without explanation. I didn't understand why it's needed.

> Please feel free to close this issue if you are not interested in fixing the error.

It's not about being interested. I'm trying to understand the issue here.

> Node.js WILL correctly handle file dependencies via require(...) so all 3 required files will be used.

Ok. I'm not familiar with package.json that well. Just don't want anything else to break.

**Comment by pilwon** [comment]
@kangax I assumed you knew well about how `package.json` worked since your module already contained customized `main` value when you could have left it with the default `index.js`. Explaining only because you asked -- I was simply referring to the error message (`require('./htmlparser')` fails to work) that brought me to open this issue in the first place, since you didn't bring the actual problem part into discussion.

So I updated my last comment and left only the problem-solution part. Let me know if you need more clarification to understand the problem and the suggestion. Thanks for sharing your project-

**Comment by cedricziel** [comment]
Any progress on this issue?

**Comment by XhmikosR** [comment]
Sounds like something isn't being exported properly.

I'll try to have a look in the next days.

**Comment by kangax** [comment]
@XhmikosR thanks!

**Comment by XhmikosR** [comment]
I personally cannot reproduce this by just using the npm package.

What are the clear instructions to reproduce the issue with the latest npm package?

**Comment by kangax** [comment]
Closing now that there's no response

**Comment by evanrs** [comment]
I have experienced the same error. I followed the solution given by @pilwon but found there were no changes to be made. To be clear, I am using rhtml@1.0.0, which points to html-minifier@0.5.4.

The error occurs only when passing in a variable as the path reference and succeeds only when passing in a string literal. Is this the expected behavior?

**Comment by TimBeyer** [comment]
This issue still exists, if you browserify `html-minifier`.  
The relative import does not work for obvious reasons (the file is not in the `dist` folder) and bundling fails.

**Comment by kangax** [comment]
> This issue still exists, if you browserify html-minifier.

Can I ask why you would need to browserify it?

**Comment by evanrs** [comment]
> Can I ask why you would need to browserify it?

Including html directly in your build is a boon for app responsiveness and code organization. For example, Angular changes views and adds directives before completing a template request. This lends itself to a clunky presentation where some or all of the page may be missing momentarily. Putting the template in the build increases the cost of the first download, but drastically improves the rest of the experience. 

It's helpful for organizing modular code. `var template = rhtml('./settings.html')` isolates the concerns of the code to that folder. The alternative `{template: '/app/account/user/settings.html'}` clutters the code with brittle references that limits reuse.

**Comment by TimBeyer** [comment]
He's got a point though, I probably should minify the templates during the build stage instead of bundling them unminified and minifying client-side, which seems kind of pointless.  
I needed it because a `html` to `virtual-dom` converter seemed to have problems with whitespace text nodes, which I wanted to get rid of using `html-minifier`

I've solved it in a different way now though.
Still, I think this is a bug and should be fixed. Who knows, maybe someone wants to build a client-side html minification service or something like that where using it with browserify makes more sense.

**Comment by kkotak** [comment]
Hi guys, this still seems to be the problem. Any updates?
