### ISSUE TITLE
There's a conflict with nested HTML comments which causes problems with grunt-contrib-usemin

### ISSUE THREAD

**Issue by stereokai** [kangax/html-minifier#90]
There's a conflict with nested HTML comments which causes problems with grunt-contrib-usemin:

```
<!--[if lt IE 9]>
<!-- build:js scripts/ieshims.js -->
<script src="bower_components/es5-shim/es5-shim.js"></script>
<script src="bower_components/json3/lib/json3.min.js"></script>
<!-- endbuild -->
<![endif]-->
```

It makes HTMLMinifier fail.

Nesting the comments the other way around results in the IE conditionals getting dropped from the minified HTML file.

For what it's worth, SublimeText 2 is signaling a syntax error with this code:
![se](https://f.cloud.github.com/assets/2685357/1319969/eed69a46-3328-11e3-9f66-211abc2de888.PNG)

As a temporary solution, I tried setting `removeComments: false` in the file, but I still get a warning.

Your help is appreciated.

**Comment by abhikp** [comment]
+1, except removeComments: false doesn't seem to fix it.

**Comment by stereokai** [comment]
That's what I said, I'm still getting a warning :)
@kangax to the rescue!

**Comment by nborko** [comment]
Strictly speaking, it isn't valid HTML since comment text must not contain two consecutive U+002D HYPHEN-MINUS characters (see http://www.w3.org/TR/html5/syntax.html#comments).  Since conditional comments only work in IE anyway, you could use the non-standard `<comment>` tag instead.

**Comment by stereokai** [comment]
Well, every day you learn something new. I didn't know there were so many restrictions within the HTML comment. I also didn't know about the IE8 comment tag, but [quirksmode](http://www.quirksmode.org/css/condcom.html) confirms it exists, and I also tested it myself. However, the IE8 `<comment>` tag will not work, because:

``` javascript
        // Comment:
        if ( html.indexOf("<!--") === 0 ) {
          index = html.indexOf("-->");
```

From: https://github.com/kangax/html-minifier/blob/gh-pages/src/htmlparser.js#L70-L72

@kangax So perhaps it would be possible to add `<comment>` and `</comment>` to the parser?

**Comment by nborko** [comment]
I wouldn't suggest adding special cases for non-standard tags, but I also didn't consider that grunt-usemin has a strict requirement to use proper HTML comments, so my suggestion is probably not helpful in that case anyway.

Treating conditional comments as special at the parser level (before https://github.com/kangax/html-minifier/blob/gh-pages/src/htmlparser.js#L70-L80) rather than at the handler level after being identified as a comment (https://github.com/kangax/html-minifier/blob/gh-pages/src/htmlminifier.js#L403-418) is probably a better solution, since semantically they're not really comments.  In that case, you'd consider `<!--[if` to be an opening tag, and `[endif]-->` to be a closing tag for parsing purposes.  However, that's going to add complexity to the parser and additional handler requirements for something that isn't even supported in standards mode on IE 10+.  And it still isn't valid HTML.

Have you tried putting the build comments outside the conditional?  If that doesn't work, I would petition the grunt-minify project to recognize it, because it's the only way to get valid HTML, and in the meantime I would suggest in this instance just to configure the concat and uglifyjs tasks manually in the gruntfile.

**Comment by stereokai** [comment]
@nborko first off, appreciate your elaborate reply. Yeah, I did try putting the build comments outside the conditional - I wrote in the original post: "Nesting the comments the other way around results in the IE conditionals getting dropped from the minified HTML file." - and the IE conditionals are of course the purpose of this issue.

By "configure manually", do you mean having separate build tasks for IE < 9 and the rest?

**Comment by nborko** [comment]
When I plug in the following code:

```
<!-- build:js scripts/ieshims.js -->
<!--[if lt IE 9]>
<script src="bower_components/es5-shim/es5-shim.js"></script>
<script src="bower_components/json3/lib/json3.min.js"></script>
<![endif]-->
<!-- endbuild -->
```

at http://kangax.github.io/html-minifier/, it works as expected.  I don't know what the output of grunt-usemin is before sending it through html-minifier, so that may be the culprit.

By "configure manually," I mean don't use the grunt-usemin directives in the HTML, and instead build scripts/ieshims.js with a normal grunt task, e.g.:

```
{
  concat: {
    '.tmp/concat/scripts/ieshims.js': [
      'bower_components/es5-shim/es5-shim.js',
      'bower_components/json3/lib/json3.min.js'
      ]
  },
  uglifyjs: {
    'scripts/ieshims.js': ['.tmp/concat/scripts/ieshims.js']
  }
}
```

HTH.

**Comment by stereokai** [comment]
That is a good solution. When you say "works as expected", what do you mean?

**Comment by nborko** [comment]
```
<!--[if lt IE 9]><script src="bower_components/es5-shim/es5-shim.js"></script>
<script src="bower_components/json3/lib/json3.min.js"></script><![endif]-->
```

That's the correct minified output of the HTML.  Of course, that will no longer work with grunt-usemin, so obviously that task has to run _before_ html-minify.  Further investigation shows there is a test case just like yours in the grunt-usemin source tree (https://github.com/yeoman/grunt-usemin/blob/master/test/fixtures/block_with_IEconditionals_within.html), so it seems like this should all work.

**Comment by stereokai** [comment]
@nborko "so obviously that task has to run before html-minify" - which one? I am confused :)

**Comment by nborko** [comment]
@stereokai In other words, your files need to be processed by the grunt-usemin processes before getting passed through html-minify, which should be the last step in the build process (or very nearly so).

**Comment by stereokai** [comment]
That's interesting, because looking at my gruntfile, usemin is the last task, but html-minifier is not there. I believe it is a dependency of usemin:

``` Javascript
   ['clean:dist',
    'useminPrepare',
    'concurrent:dist',
    'autoprefixer',
    'concat',
    'copy:dist',
    'cdnify',
    'ngmin',
    'cssmin',
    'usemin']
```

**Comment by nborko** [comment]
OK, I think I realize the disconnect.  I didn't read closely enough and just assumed you were using https://github.com/yeoman/grunt-usemin, but I see you are using an (old) fork.  Try using the original (and currently maintained) project at that URL.

**Comment by stereokai** [comment]
What fork am I using? I'd like to look it up to know what exactly do I have to change now in the Grunt workflow...

**Comment by nborko** [comment]
You stated you are using grunt-contrib-usemin (apparently at https://github.com/tinganho/grunt-contrib-usemin), which is a fork of grunt-usemin (at https://github.com/yeoman/grunt-usemin).  I'm not sure how you got to your current build environment, but you'd want to delete grunt-contrib-usemin from your node_modules and either use npm or manually install grunt-usemin.  It should work without any changes to your config file(s).

You should probably back up your current build configuration before deleting anything.

**Comment by stereokai** [comment]
I am not sure either. The guy that scaffolded the project I'm working on was only working here for a week, and he left long ago. I don't know what Yeoman generator he used. There are only 20 results in the Google machine for "grunt-contrib-usemin". I have a hunch you might be right :)

I'll give it a go tomorrow and let you know. Thank you for your time!

**Comment by kangax** [comment]
Closing as per @nborko's comments
