### ISSUE TITLE
"remove-optional-tags" breaks OG tags on Linkedin

### ISSUE THREAD

**Issue by diegotrigo** [kangax/html-minifier#998]
Heads up that the option "remove-optional-tags" breaks OG tags on Linkedin.
Linkeding can't pull image, copy etc.. 

I supposed is due the fact that "remove-optional-tags" removes "head", which is not that optional then.

Just wanted to flag it here, after spending 2 hours trying to find out why the hell Linkedin wasn't working.

**Comment by DamonHD** [comment]
Nominally, ie according to spec, head and body and so on are optional.  Absence of head confuses Bing's parser but absence of body is fine.  AMP requires head and body despite being a product of Google which otherwise recommends omitting head and body.

(Take any set of matching www. m. and amp. pages on my earth.org.uk site to see the handling of those tags for that case.  I only apply this minifier to the m. pages as a result.)

So, there is some inconsistency, but the HTML5 spec details that they are indeed optional, and how to infer where they would be to manage without them.

Rgds

Damon

**Comment by XhmikosR** [comment]
Well, the specs are the only thing everyone can be sure about.

If it's causing you issues just remove the option. But IMO you should bug them to fix this on their side or change the specs.

**Comment by DamonHD** [comment]
Note that the AMP specs require that html/head/body tags be left in place.  See my other open issue to ask if we could have an easy way to keep these always (while omitting other redundant tags as usual) which would fix these common use cases (Bing/LI/AMP)...
